pokemon = [
  "mew", "unown", "magikarp", "mudkip", "pikachu", "grovyle", "ampharos",
  "blastoise", "wailord", "snorlax", "garchomp",
  "jirachi", "hooh", "kyogre", "groudon", "giratina", "arceus",
  "rayquaza", "darkrai",
  "gallade", "heracross", "shuckle", "breloom",
  "chansey", "tyranitar", "gengar", "dragonite", "gyarados", "salamence",
  "lugia", "lapras", "turtwig", "scizor",
  "lopunny", "megalopunny",
  "beedrill", "megabeedrill",
  "charizard", "megacharizardx", "megacharizardy",
  "megaheracross", "megasnorlax", "megascizor",
  "kangaskhan", "megakangaskhan",
  "sableye", "megasableye",
  "ditto", "eevee",
  "twinlatios", "twinlatias", "twinslatioslatias",
  "mewtwo", "megamewtwox", "megamewtwoy",
]
